logger:
 filename: './log/log/logger.log' 
 maxsize: 50                  
 maxsave: 1                
 maxNumbers: 4                     
 compress: true  
server:
 host: 'localhost'
 port: ':8888'
grpcserver:
 host: 'localhost'
 port: ':50051'
redis:
 port: '106.14.30.173:6379'
 password: 'wasd2002'
jwt: 'pR(IUyOnZQ?I)2n`&{Z=]bAlNvR}Hy'
redisclock:
  register: 'register-clock'
  login: 'login-clock'